### ISSUE TITLE
http UI: 8086 is not working after installing influxdb on my server

### ISSUE THREAD

**Issue by hemanthog** [influxdata/influxdb.com#557]
Admin UI 8083 is working fine for me.

When i try to hit http UI, its showing "404 page not found"

Please help me out.

**Comment by rossmcdonald** [comment]
@hemanthog This repository is deprecated. Please open an issue against the [InfluxDB repository](https://github.com/influxdata/influxdb). Also be sure to include your InfluxDB version and explicit steps to reproduce the issue.

**Comment by beckettsean** [comment]
@hemanthog 8086 is merely an HTTP endpoint. There is no UI there to show in a browser. It is not valid to hit 8086 with a web browser.
